In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
pd.set_option('max_rows',500)
pd.set_option('max_columns',500)
train_df = pd.read_csv('happiness_train_abbr.csv')
test_df = pd.read_csv('happiness_test_abbr.csv')
combine=[train_df,test_df]
train_df.head()

,id,happiness,survey_type,province,city,county,survey_time,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability
0,1,4,1,12,32,59,2015/8/4 14:18,1,1959,1,1,1,11,20000,1,45.0,176,155,3,2,5,5,2,4,3,3,3,1,3.0,30.0,1.0,2.0,60000.0,2,2,1,2,3,3,2,4,3
1,2,4,2,18,52,85,2015/7/21 15:04,1,1992,1,1,1,12,20000,1,110.0,170,110,5,4,3,1,2,4,3,3,6,1,3.0,2.0,1.0,3.0,40000.0,3,4,1,2,1,1,1,4,2
2,3,4,2,29,83,126,2015/7/21 13:24,2,1967,1,0,3,4,2000,1,120.0,160,122,4,4,5,1,3,4,2,4,5,2,NaN,NaN,NaN,NaN,8000.0,3,3,1,2,3,2,1,4,2
3,4,5,2,10,28,51,2015/7/25 17:33,2,1943,1,1,1,3,6420,1,78.0,163,170,4,4,4,1,2,4,4,4,5,4,NaN,NaN,NaN,NaN,12000.0,3,3,1,1,7,2,1,3,2
4,5,4,1,7,18,36,2015/8/10 9:50,2,1994,1,1,1,12,-1,2,70.0,165,110,5,5,3,2,4,3,4,2,1,6,NaN,NaN,NaN,NaN,-2.0,4,3,1,1,1,3,2,3,-8

In [3]:
train_df.describe()

,id,happiness,survey_type,province,city,county,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability
count,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000,8000.000000,8000.00000,8000.000000,8000.000000,8000.000000,8.000000e+03,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000,8000.000000,8000.000000,8000.000000,2951.000000,2951.000000,2951.000000,2951.000000,7.999000e+03,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000,8000.000000
mean,4000.50000,3.850125,1.405500,15.155375,42.564750,70.619000,1.53000,1964.707625,1.37350,0.772250,1.427250,4.878375,3.330734e+04,1.317750,115.302954,163.989750,121.575625,3.598500,3.786250,3.819375,1.893750,2.790625,3.291000,1.92650,3.135125,4.192250,2.979750,3.155202,14.500508,0.906811,2.652321,6.776050e+04,2.882500,2.595875,1.063625,1.817125,3.234375,2.226125,1.702500,3.30350,1.094875
std,2309.54541,0.938228,0.491019,8.917100,27.187404,38.747503,0.49913,16.842865,1.52882,1.071459,1.408441,3.154533,2.329853e+05,1.141358,87.275890,8.086567,23.189453,1.108468,1.372332,1.062846,1.348588,1.083021,1.076668,1.19343,1.285524,2.040358,1.752705,1.759518,11.467829,1.404517,1.716054,2.909591e+05,1.521835,1.077011,0.789402,0.511825,1.423182,0.971525,0.976147,1.98132,3.410180
min,1.00000,-8.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1921.000000,-8.00000,-8.000000,-8.000000,-8.000000,-3.000000e+00,-8.000000,3.000000,114.000000,40.000000,-8.000000,-8.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.00000,-8.000000,-8.000000,1.000000,-8.000000,-3.000000,-8.000000,-8.000000,-3.000000e+00,-3.000000,-8.000000,-3.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.00000,-8.000000
25%,2000.75000,4.000000,1.000000,7.000000,18.000000,37.000000,1.00000,1952.000000,1.00000,1.000000,1.000000,3.000000,1.695000e+03,1.000000,64.000000,158.000000,105.000000,3.000000,3.000000,3.000000,1.000000,2.000000,3.000000,1.00000,2.000000,3.000000,1.000000,3.000000,5.000000,1.000000,2.000000,1.300000e+04,2.000000,2.000000,1.000000,2.000000,3.000000,2.000000,1.000000,3.00000,2.000000
50%,4000.50000,4.000000,1.000000,15.000000,42.000000,73.000000,2.00000,1965.000000,1.00000,1.000000,1.000000,4.000000,1.500000e+04,1.000000,96.000000,164.000000,120.000000,4.000000,4.000000,4.000000,1.000000,3.000000,3.000000,2.00000,3.000000,5.000000,3.000000,3.000000,12.000000,1.000000,3.000000,3.800000e+04,3.000000,3.000000,1.000000,2.000000,3.000000,2.000000,2.000000,4.00000,2.000000
75%,6000.25000,4.000000,2.000000,22.000000,65.000000,104.000000,2.00000,1977.000000,1.00000,1.000000,1.000000,6.000000,3.600000e+04,1.000000,130.000000,170.000000,135.250000,4.000000,5.000000,5.000000,2.000000,4.000000,4.000000,3.00000,4.000000,5.000000,5.000000,3.000000,22.000000,1.000000,3.000000,7.000000e+04,4.000000,3.000000,1.000000,2.000000,3.000000,3.000000,2.000000,4.00000,3.000000
max,8000.00000,5.000000,2.000000,31.000000,89.000000,134.000000,2.00000,1997.000000,8.00000,1.000000,9.000000,14.000000,9.999990e+06,4.000000,1300.000000,191.000000,260.000000,5.000000,5.000000,5.000000,8.000000,5.000000,5.000000,5.00000,5.000000,10.000000,6.000000,9.000000,55.000000,2.000000,4.000000,9.999992e+06,50.000000,5.000000,30.000000,2.000000,7.000000,3.000000,3.000000,5.00000,4.000000

In [4]:
train_df.corr()

,id,happiness,survey_type,province,city,county,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability
id,1.000000,0.009560,-0.011345,-0.010624,-0.008390,-0.008109,0.021515,-0.000808,0.000470,0.002805,0.003557,0.016327,0.001647,0.010574,-0.004246,-0.017512,-0.024580,0.008466,0.003982,0.010735,0.018732,0.002917,0.008571,0.017032,0.000947,0.008587,0.016033,0.021452,-0.026075,0.004710,0.003727,0.016315,-0.007322,0.013052,-0.005744,-0.014820,0.007040,-0.004911,0.015799,0.015835,-0.014626
happiness,0.009560,1.000000,-0.017043,-0.007333,-0.009733,-0.007544,0.022016,-0.007805,-0.018928,0.063539,0.002296,0.102945,0.024056,0.094677,0.046945,0.030380,0.074584,0.246979,0.182414,0.299933,0.057366,0.103588,0.134761,0.116214,0.245552,0.267328,0.002564,0.026440,-0.009747,0.065813,0.020994,0.047654,0.054821,0.235988,0.103013,-0.012826,-0.026026,-0.084743,-0.022892,0.112572,0.002179
survey_type,-0.011345,-0.017043,1.000000,0.090110,0.087598,0.092077,-0.018017,-0.093246,0.113639,-0.009310,0.009039,-0.380103,-0.055283,-0.128663,0.285112,-0.122626,-0.120172,-0.108766,-0.134803,-0.098947,-0.460906,0.124646,-0.096719,-0.273407,0.062913,-0.077324,0.032058,0.062155,-0.072869,0.049296,0.027009,-0.064711,0.088196,-0.033573,0.045670,0.119012,0.035366,0.056462,-0.017452,0.000957,0.005392
province,-0.010624,-0.007333,0.090110,1.000000,0.997278,0.994408,-0.006174,0.006830,-0.097896,0.040080,0.011496,-0.106921,-0.014472,-0.012529,0.036237,-0.034290,-0.037169,-0.029165,-0.024665,-0.056911,-0.082106,0.013803,0.047389,-0.088419,-0.028562,-0.064191,0.001313,-0.004242,0.016210,0.028482,0.047849,-0.013049,0.017679,-0.015760,0.015982,0.052053,0.012458,0.018672,-0.009410,0.015268,-0.020424
city,-0.008390,-0.009733,0.087598,0.997278,1.000000,0.996885,-0.005394,0.004688,-0.096685,0.040693,0.012346,-0.105340,-0.014301,-0.011464,0.043159,-0.037190,-0.041749,-0.028292,-0.025667,-0.056926,-0.077499,0.016380,0.047040,-0.084527,-0.029973,-0.061231,0.000258,-0.008911,0.019655,0.029514,0.047451,-0.012701,0.020235,-0.012963,0.018096,0.051562,0.012068,0.017718,-0.011498,0.013936,-0.023855
county,-0.008109,-0.007544,0.092077,0.994408,0.996885,1.000000,-0.003081,0.009343,-0.094663,0.041588,0.017564,-0.111123,-0.015008,-0.013861,0.054781,-0.041439,-0.044681,-0.023227,-0.024405,-0.057967,-0.080426,0.021973,0.047263,-0.086338,-0.030831,-0.058502,-0.002696,-0.009860,0.018185,0.032150,0.052773,-0.013315,0.029314,-0.010391,0.019728,0.050938,0.010450,0.018758,-0.010586,0.012827,-0.027537
gender,0.021515,0.022016,-0.018017,-0.006174,-0.005394,-0.003081,1.000000,-0.000392,-0.005184,-0.042858,0.066413,-0.107928,-0.029193,-0.127775,-0.006917,-0.664144,-0.417030,-0.071547,-0.074775,-0.044810,-0.021451,0.030238,0.012599,-0.082975,-0.018496,0.009926,0.172607,-0.001099,-0.138281,-0.048346,0.009909,-0.017419,0.001020,-0.013607,-0.016426,0.010957,0.147348,0.015012,-0.007338,-0.036640,-0.098218
birth,-0.000808,-0.007805,-0.093246,0.006830,0.004688,0.009343,-0.000392,1.000000,0.001930,0.032991,-0.035102,0.438542,0.042557,-0.029172,0.025649,0.239992,0.093676,0.372044,0.296968,0.119919,-0.051552,0.034639,-0.042952,0.273202,-0.106343,0.038174,-0.356564,-0.046485,-0.620254,0.091261,0.044880,0.047316,0.236916,0.059570,-0.002164,-0.161693,-0.497794,-0.003125,-0.047576,0.071264,-0.003911
nationality,0.000470,-0.018928,0.113639,-0.097896,-0.096685,-0.094663,-0.005184,0.001930,1.000000,-0.049568,0.106270,-0.072286,-0.019923,-0.016581,0.135042,-0.066117,-0.062807,-0.028868,-0.000198,-0.017641,-0.083224,0.080609,-0.005963,-0.031408,0.032648,-0.046347,-0.000210,0.057677,-0.038444,0.007692,0.023283,-0.024934,0.070126,-0.034734,0.035312,0.038732,0.005096,0.048089,0.022277,0.007889,0.017421
religion,0.002805,0.063539,-0.009310,0.040080,0.040693,0.041588,-0.042858,0.032991,-0.049568,1.000000,-0.129528,0.059121,0.008029,0.043849,-0.026628,0.050909,0.042299,0.068679,0.057691,0.044120,0.014398,0.012122,0.006199,0.018388,0.034054,0.036386,-0.034010,0.037611,-0.003312,0.032930,0.031850,0.012010,0.006587,0.054783,0.011222,0.020928,-0.043941,0.042995,0.062628,0.060124,0.019737
religion_freq,0.003557,0.002296,0.009039,0.011496,0.012346,0.017564,0.066413,-0.035102,0.106270,-0.129528,1.000000,-0.079666,-0.009406,-0.035157,0.029565,-0.069656,-0.042512,-0.031203,-0.041486,-0.033958,0.003697,0.018493,0.011901,-0.018875,-0.020635,-0.002571,0.036271,0.035347,0.020066,0.047985,0.023129,0.001562,0.007327,-0.009123,0.024572,0.015273,0.035108,0.009146,-0.003650,-0.020086,-0.012553
edu,0.016327,0.102945,-0.380103,-0.106921,-0.105340,-0.111123,-0.107928,0.438542,-0.072286,0.059121,-0.079666,1.000000,0.077639,0.300318,-0.108884,0.290116,0.141998,0.259933,0.249219,0.174812,0.320039,-0.013127,0.112161,0.516288,-0.006891,0.173490,-0.202136,-0.018147,-0.102241,0.018734,-0.085450,0.108860,-0.016935,0.153140,0.017315,-0.194112,-0.299821,-0.105161,-0.030062,0.084575,0.032624
income,0.001647,0.024056,-0.055283,-0.014472,-0.014301,-0.015008,-0.029193,0.042557,-0.019923,0.008029,-0.009406,0.077639,1.000000,0.023217,-0.006822,0.040284,0.047459,0.039897,0.034149,0.020486,0.035482,0.000372,-0.020111,0.052534,0.003184,0.038449,-0.064664,-0.034073,-0.007951,0.005288,-0.023583,0.103992,-0.002591,0.033378,0.020801,-0.038205,-0.014283,-0.023323,-0.009948,0.008913,0.016998
political,0.010574,0.094677,-0.128663,-0.012529,-0.011464,-0.013861,-0.127775,-0.029172,-0.016581,0.043849,-0.035157,0.300318,0.023217,1.000000,-0.032903,0.131739,0.109543,0.078025,0.085510,0.098124,0.152132,0.030668,0.109086,0.254948,0.046395,0.098900,0.023340,0.031081,0.095564,0.044299,-0.006839,0.034115,-0.049829,0.098577,0.039720,-0.029989,-0.049624,-0.056688,0.035822,0.044309,0.018174
floor_area,-0.004246,0.046945,0.285112,0.036237,0.043159,0.054781,-0.006917,0.025649,0.135042,-0.026628,0.029565,-0.108884,-0.006822,-0.032903,1.000000,-0.029154,-0.028199,0.045335,-0.005247,0.012551,-0.139880,0.108013,-0.017219,-0.070743,0.034779,0.067098,-0.037435,-0.008227,0.019205,0.009858,0.013320,0.005914,0.211630,0.096404,0.099153,-0.039004,-0.037035,-0.050624,-0.040112,-0.014434,-0.017011
height_cm,-0.017512,0.030380,-0.122626,-0.034290,-0.037190,-0.041439,-0.664144,0.239992,-0.066117,0.050909,-0.069656,0.290116,0.040284,0.131739,-0.029154,1.000000,0.561909,0.197614,0.153945,0.113051,0.079836,-0.055259,0.010911,0.193364,-0.015537,0.052241,-0.214352,-0.000985,0.018619,0.037147,-0.034759,0.031344,0.016847,0.062051,0.022878,-0.090403,-0.245615,-0.040044,0.009670,0.075740,0.085331
weight_jin,-0.024580,0.074584,-0.120172,-0.037169,-0.041749,-0.044681,-0.417030,0.093676,-0.062807,0.042299,-0.042512,0.141998,0.047459,0.109543,-0.028199,0.561909,1.000000,0.095806,0.108201,0.093298,0.106452,-0.022354,0.034309,0.087253,-0.018097,0.058548,-0.135712,-0.005989,0.123172,-0.004687,-0.035488,0.022622,0.034876,0.054406,0.023370,-0.084115,-0.118976,-0.040521,0.026554,0.066876,0.094933
health,0.008466,0.246979,-0.108766,-0.029165,-0.028292,-0.023227,-0.071547,0.372044,-0.028868,0.068679,-0.031203,0.259933,0.039897,0.078025,0.045335,0.197614,0.095806,1.000000,0.537595,0.424437,0.031506,0.122307,0.061771,0.238895,0.047377,0.177297,-0.205529,0.026473,-0.105020,0.113739,0.100860,0.055289,0.099424,0.213200,0.040913,-0.063328,-0.204313,-0.067411,-0.022942,0.097671,0.038587
health_problem,0.003982,0.182414,-0.134803,-0.024665,-0.025667,-0.024405,-0.074775,0.296968,-0.000198,0.057691,-0.041486,0.249219,0.034149,0.085510,-0.005247,0.153945,0.108201,0.537595,1.000000,0.454535,0.064059,0.083438,0.078147,0.218563,0.047483,0.150094,-0.177424,0.063795,-0.034516,0.109841,0.140329,0.056724,0.072615,0.136513,0.048560,-0.024511,-0.154021,-0.056947,0.001332,0.089610,0.077876
depression,0.010735,0.299933,-0.098947,-0.056911,-0.056926,-0.057967,-0.044810,0.119919,-0.017641,0.044120,-0.033958,0.174812,0.020486,0.098124,0.012551,0.113051,0.093298,0.424437,0.454535,1.000000,0.079236,0.087478,0.109520,0.156294,0.123089,0.185617,-0.064107,0.050836,-0.010977,0.117934,0.123362,0.046171,0.042526,0.153885,0.057804,0.005917,-0.073915,-0.050033,0.026644,0.089498,0.040290
hukou,0.018732,0.057366,-0.460906,-0.082106,-0.077499,-0.080426,-0.021451,-0.051552,-0.083224,0.014398,0.003697,0.320039,0.035482,0.152132,-0.139880,0.079836,0.106452,0.031506,0.064059,0.079236,1.000000,-0.066847,0.119193,0.243789,-0.008952,0.097656,0.040133,-0.019526,0.195456,-0.009970,-0.047939,0.069263,-0.084176,0.058572,0.020560,-0.111287,0.006202,-0.085666,-0.015183,0.014269,0.024755
socialize,0.002917,0.103588,0.124646,0.013803,0.016380,0.021973,0.030238,0.034639,0.080609,0.012122,0.018493,-0.013127,0.000372,0.030668,0.108013,-0.055259,-0.022354,0.122307,0.083438,0.087478,-0.066847,1.000000,0.213077,0.100678,0.051841,0.084297,-0.014615,0.061058,0.005240,0.051989,0.038347,0.029399,0.038471,0.099364,0.080216,0.048192,-0.002224,-0.016900,0.013089,0.048028,0.004025
relax,0.008571,0.134761,-0.096719,0.047389,0.047040,0.047263,0.012599,-0.042952,-0.005963,0.006199,0.011901,0.112161,-0.020111,0.109086,-0.017219,0.010911,0.034309,0.061771,0.078147,0.109520,0.119193,0.213077,1.000000,0.216489,0.037794,0.059437,0.090107,0.084291,0.042182,0.045163,0.057329,0.030900,-0.024679,0.057658,0.037196,0.027617,0.012595,-0.028734,0.016960,0.047496,-0.018348
learn,0.017032,0.116214,-0.273407,-0.088419,-0.084527,-0.086338,-0.082975,0.273202,-0.031408,0.018388,-0.018875,0.516288,0.052534,0.254948,-0.070743,0.193364,0.087253,0.238895,0.218563,0.156294,0.243789,0.100678,0.216489,1.000000,0.019349,0.142934,-0.087433,0.015687,-0.017446,0.056285,-0.015628,0.080921,-0.010951,0.145055,0.036149,-0.085250,-0.209861,-0.075157,-0.020811,0.092336,0.017103
equity,0.000947,0.245552,0.062913,-0.028562,-0.029973,-0.030831,-0.018496,-0.106343,0.032648,0.034054,-0.020635,-0.006891,0.003184,0.046395,0.034779,-0.015537,-0.018097,0.047377,0.047483,0.123089,-0.008952,0.051841,0.037794,0.019349,1.000000,0.148048,0.041108,0.008836,0.001741,0.015064,0.018985,0.019114,-0.028180,0.107348,0.037971,0.052192,0.055051,-0.022166,0.014704,0.143907,0.023482
class,0.008587,0.267328,-0.077324,-0.064191,-0.061231,-0.058502,0.009926,0.038174,-0.046347,0.036386,-0.002571,0.173490,0.038449,0.098900,0.067098,0.052241,0.058548,0.177297,0.150094,0.185617,0.097656,0.084297,0.059437,0.142934,0.148048,1.000000,-0.042399,-0.018049,0.028616,0.077898,-0.008328,0.073110,0.034936,0.303768,0.072661,-0.079697,-0.054309,-0.121138,-0.008125,0.120860,0.057371
work_exper,0.016033,0.002564,0.032058,0.001313,0.000258,-0.002696,0.172607,-0.356564,-0.000210,-0.034010,0.036271,-0.202136,-0.064664,0.023340,-0.037435,-0.214352,-0.135712,-0.205529,-0.177424,-0.064107,0.040133,-0.014615,0.090107,-0.087433,0.041108,-0.042399,1.000000,NaN,NaN,NaN,NaN,-0.052965,-0.086054,-0.057384,-0.007924,0.144567,0.148298,0.010031,0.035352,-0.045138,-0.284073
work_status,0.021452,0.026440,0.062155,-0.004242,-0.008911,-0.009860,-0.001099,-0.046485,0.057677,0.037611,0.035347,-0.018147,-0.034073,0.031081,-0.008227,-0.000985,-0.005989,0.026473,0.063795,0.050836,-0.019526,0.061058,0.084291,0.015687,0.008836,-0.018049,NaN,1.000000,0.055922,0.033151,0.122510,-0.064178,-0.023737,-0.008277,0.003430,0.141042,-0.014379,0.081275,0.069828,0.001365,0.063885
work_yr,-0.026075,-0.009747,-0.072869,0.016210,0.019655,0.018185,-0.138281,-0.620254,-0.038444,-0.003312,0.020066,-0.102241,-0.007951,0.095564,0.019205,0.018619,0.123172,-0.105020,-0.034516,-0.010977,0.195456,0.005240,0.042182,-0.017446,0.001741,0.028616,NaN,0.055922,1.000000,0.000834,-0.018801,-0.020190,-0.068204,0.026066,0.035598,0.003209,0.295707,0.008925,0.110925,0.010497,0.038553
work_type,0.004710,0.065813,0.049296,0.028482,0.029514,0.032150,-0.048346,0.091261,0.007692,0.032930,0.047985,0.018734,0.005288,0.044299,0.009858,0.037147,-0.004687,0.113739,0.109841,0.117934,-0.009970,0.051989,0.045163,0.056285,0.015064,0.077898,NaN,0.033151,0.000834,1.000000,0.448708,-0.051244,0.042419,0.091253,0.024209,0.047941,-0.056924,0.023893,0.013930,0.051727,0.185583
work_manage,0.003727,0.020994,0.027009,0.047849,0.047451,0.052773,0.009909,0.044880,0.023283,0.031850,0.023129,-0.085450,-0.023583,-0.006839,0.013320,-0.034759,-0.035488,0.100860,0.140329,0.123362,-0.047939,0.038347,0.057329,-0.015628,0.018985,-0.008328,NaN,0.122510,-0.018801,0.448708,1.000000,-0.084343,-0.000723,0.049940,0.025033,0.177882,0.015196,0.082479,0.052381,0.023483,0.134379
family_income,0.016315,0.047654,-0.064711,-0.013049,-0.012701,-0.013315,-0.017419,0.047316,-0.024934,0.012010,0.001562,0.108860,0.103992,0.034115,0.005914,0.031344,0.022622,0.055289,0.056724,0.046171,0.069263,0.029399,0.030900,0.080921,0.019114,0.073110,-0.052965,-0.064178,-0.020190,-0.051244,-0.084343,1.000000,0.009596,0.074066,0.069100,-0.074526,-0.022778,-0.040928,-0.003752,0.011436,-0.003745
family_m,-0.007322,0.054821,0.088196,0.017679,0.020235,0.029314,0.001020,0.236916,0.070126,0.006587,0.007327,-0.016935,-0.002591,-0.049829,0.211630,0.016847,0.034876,0.099424,0.072615,0.042526,-0.084176,0.038471,-0.024679,-0.010951,-0.028180,0.034936,-0.086054,-0.023737,-0.068204,0.042419,-0.000723,0.009596,1.000000,0.055461,0.077299,-0.101902,-0.154329,0.008841,-0.010911,0.014150,-0.016472
family_status,0.013052,0.235988,-0.033573,-0.015760,-0.012963,-0.010391,-0.013607,0.059570,-0.034734,0.054783,-0.009123,0.153140,0.033378,0.098577,0.096404,0.062051,0.054406,0.213200,0.136513,0.153885,0.058572,0.099364,0.057658,0.145055,0.107348,0.303768,-0.057384,-0.008277,0.026066,0.091253,0.049940,0.074066,0.055461,1.000000,0.103769,-0.062874,-0.059072,-0.112302,-0.005924,0.129428,0.041552
house,-0.005744,0.103013,0.045670,0.015982,0.018096,0.019728,-0.016426,-0.002164,0.035312,0.011222,0.024572,0.017315,0.020801,0.039720,0.099153,0.022878,0.023370,0.040913,0.048560,0.057804,0.020560,0.080216,0.037196,0.036149,0.037971,0.072661,-0.007924,0.003430,0.035598,0.024209,0.025033,0.069100,0.077299,0.103769,1.000000,-0.021633,-0.010604,-0.025934,-0.011936,0.031294,0.007138
car,-0.014820,-0.012826,0.119012,0.052053,0.051562,0.050938,0.010957,-0.161693,0.038732,0.020928,0.015273,-0.194112,-0.038205,-0.029989,-0.039004,-0.090403,-0.084115,-0.063328,-0.024511,0.005917,-0.111287,0.048192,0.027617,-0.085250,0.052192,-0.079697,0.144567,0.141042,0.003209,0.047941,0.177882,-0.074526,-0.101902,-0.062874,-0.021633,1.000000,0.078071,0.158346,0.098527,0.003208,0.001848
marital,0.007040,-0.026026,0.035366,0.012458,0.012068,0.010450,0.147348,-0.497794,0.005096,-0.043941,0.035108,-0.299821,-0.014283,-0.049624,-0.037035,-0.245615,-0.118976,-0.204313,-0.154021,-0.073915,0.006202,-0.002224,0.012595,-0.209861,0.055051,-0.054309,0.148298,-0.014379,0.295707,-0.056924,0.015196,-0.022778,-0.154329,-0.059072,-0.010604,0.078071,1.000000,0.029568,0.043538,-0.046998,0.014067
status_peer,-0.004911,-0.084743,0.056462,0.018672,0.017718,0.018758,0.015012,-0.003125,0.048089,0.042995,0.009146,-0.105161,-0.023323,-0.056688,-0.050624,-0.040044,-0.040521,-0.067411,-0.056947,-0.050033,-0.085666,-0.016900,-0.028734,-0.075157,-0.022166,-0.121138,0.010031,0.081275,0.008925,0.023893,0.082479,-0.040928,0.008841,-0.112302,-0.025934,0.158346,0.029568,1.000000,0.379150,0.060268,0.038918
status_3_before,0.015799,-0.022892,-0.017452,-0.009410,-0.011498,-0.010586,-0.007338,-0.047576,0.022277,0.062628,-0.003650,-0.030062,-0.009948,0.035822,-0.040112,0.009670,0.026554,-0.022942,0.001332,0.026644,-0.015183,0.013089,0.016960,-0.020811,0.014704,-0.008125,0.035352,0.069828,0.110925,0.013930,0.052381,-0.003752,-0.010911,-0.005924,-0.011936,0.098527,0.043538,0.379150,1.000000,0.065824,0.061471
view,0.015835,0.112572,0.000957,0.015268,0.013936,0.012827,-0.036640,0.071264,0.007889,0.060124,-0.020086,0.084575,0.008913,0.044309,-0.014434,0.075740,0.066876,0.097671,0.089610,0.089498,0.014269,0.048028,0.047496,0.092336,0.143907,0.120860,-0.045138,0.001365,0.010497,0.051727,0.023483,0.011436,0.014150,0.129428,0.031294,0.003208,-0.046998,0.060268,0.065824,1.000000,0.131935
inc_ability,-0.014626,0.002179,0.005392,-0.020424,-0.023855,-0.027537,-0.098218,-0.003911,0.017421,0.019737,-0.012553,0.032624,0.016998,0.018174,-0.017011,0.085331,0.094933,0.038587,0.077876,0.040290,0.024755,0.004025,-0.018348,0.017103,0.023482,0.057371,-0.284073,0.063885,0.038553,0.185583,0.134379,-0.003745,-0.016472,0.041552,0.007138,0.001848,0.014067,0.038918,0.061471,0.131935,1.000000

In [5]:
train_df=train_df[(train_df['happiness']>=1)&(train_df['happiness']<=5)]

In [6]:
train_df.describe()

,id,happiness,survey_type,province,city,county,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability
count,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.00000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7.988000e+03,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,2946.000000,2946.000000,2946.000000,2946.000000,7.987000e+03,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000
mean,4001.603906,3.867927,1.405984,15.161617,42.583250,70.64647,1.530295,1964.702303,1.374061,0.776915,1.427016,4.881698,3.334375e+04,1.319980,115.356113,163.984977,121.575238,3.601277,3.788558,3.822609,1.893090,2.793440,3.294191,1.928643,3.139960,4.200551,2.979594,3.163272,14.503394,0.912424,2.658859,6.782375e+04,2.882699,2.601152,1.065223,1.819479,3.234477,2.229469,1.705809,3.310466,1.100275
std,2309.864374,0.818717,0.491112,8.915476,27.184344,38.73718,0.499113,16.848414,1.529899,1.053975,1.408912,3.149408,2.331573e+05,1.132188,87.318410,8.085915,23.189541,1.093424,1.360236,1.045936,1.348626,1.069816,1.062033,1.182979,1.267597,2.018157,1.752412,1.736697,11.458117,1.386254,1.694709,2.911651e+05,1.520820,1.051287,0.786054,0.487953,1.423383,0.951588,0.958423,1.962336,3.403146
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1921.000000,-8.000000,-8.000000,-8.000000,-8.000000,-3.000000e+00,-8.000000,3.000000,114.000000,40.000000,-8.000000,-8.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.000000,-8.000000,-8.000000,1.000000,-8.000000,-3.000000,-8.000000,-8.000000,-3.000000e+00,-3.000000,-8.000000,-3.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.000000,-8.000000
25%,2001.750000,4.000000,1.000000,7.000000,18.000000,37.00000,1.000000,1952.000000,1.000000,1.000000,1.000000,3.000000,1.780000e+03,1.000000,64.000000,158.000000,105.000000,3.000000,3.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,3.000000,1.000000,3.000000,5.000000,1.000000,2.000000,1.300000e+04,2.000000,2.000000,1.000000,2.000000,3.000000,2.000000,1.000000,3.000000,2.000000
50%,4003.500000,4.000000,1.000000,15.000000,42.000000,73.00000,2.000000,1965.000000,1.000000,1.000000,1.000000,4.000000,1.500000e+04,1.000000,96.000000,164.000000,120.000000,4.000000,4.000000,4.000000,1.000000,3.000000,3.000000,2.000000,3.000000,5.000000,3.000000,3.000000,12.000000,1.000000,3.000000,3.820800e+04,3.000000,3.000000,1.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000
75%,6002.250000,4.000000,2.000000,22.000000,65.000000,104.00000,2.000000,1977.000000,1.000000,1.000000,1.000000,6.000000,3.600000e+04,1.000000,130.000000,170.000000,135.250000,4.000000,5.000000,5.000000,2.000000,4.000000,4.000000,3.000000,4.000000,5.000000,5.000000,3.000000,22.000000,1.000000,3.000000,7.000000e+04,4.000000,3.000000,1.000000,2.000000,3.000000,3.000000,2.000000,4.000000,3.000000
max,8000.000000,5.000000,2.000000,31.000000,89.000000,134.00000,2.000000,1997.000000,8.000000,1.000000,9.000000,14.000000,9.999990e+06,4.000000,1300.000000,191.000000,260.000000,5.000000,5.000000,5.000000,8.000000,5.000000,5.000000,5.000000,5.000000,10.000000,6.000000,9.000000,55.000000,2.000000,4.000000,9.999992e+06,50.000000,5.000000,30.000000,2.000000,7.000000,3.000000,3.000000,5.000000,4.000000

In [7]:
train_df[['gender','happiness']].groupby('gender',as_index=False).mean().sort_values(by='happiness',ascending=False)

   gender  happiness
1       2   3.880784
0       1   3.853412

In [8]:
train_df['Age']=2019-train_df['birth']

/home/ning/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [9]:
train_df['Age'].describe()

count    7988.000000
mean       54.297697
std        16.848414
min        22.000000
25%        42.000000
50%        54.000000
75%        67.000000
max        98.000000
Name: Age, dtype: float64

In [10]:
train_df['AgeBand']=pd.cut(train_df['Age'],4)
train_df[['AgeBand','happiness']].groupby('AgeBand',as_index=False).mean().sort_values(by='happiness',\
                                                                                      ascending=False)

/home/ning/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

          AgeBand  happiness
3    (79.0, 98.0]   3.962963
0  (21.924, 41.0]   3.923270
2    (60.0, 79.0]   3.904628
1    (41.0, 60.0]   3.781101

In [11]:
test_df['Age']=2019-test_df['birth']
test_df['Age'].describe()

count    2968.000000
mean       54.679919
std        17.044203
min        22.000000
25%        42.000000
50%        54.000000
75%        67.000000
max        99.000000
Name: Age, dtype: float64

In [12]:
train_df.loc[train_df['Age']<=41,'Age']=0
train_df.loc[(train_df['Age']>41)&(train_df['Age']<=60),'Age']=1
train_df.loc[(train_df['Age']>60)&(train_df['Age']<=79),'Age']=2
train_df.loc[(train_df['Age']>79),'Age']=3
    
train_df.head()

/home/ning/anaconda2/envs/py36/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,id,happiness,survey_type,province,city,county,survey_time,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability,Age,AgeBand
0,1,4,1,12,32,59,2015/8/4 14:18,1,1959,1,1,1,11,20000,1,45.0,176,155,3,2,5,5,2,4,3,3,3,1,3.0,30.0,1.0,2.0,60000.0,2,2,1,2,3,3,2,4,3,1,"(41.0, 60.0]"
1,2,4,2,18,52,85,2015/7/21 15:04,1,1992,1,1,1,12,20000,1,110.0,170,110,5,4,3,1,2,4,3,3,6,1,3.0,2.0,1.0,3.0,40000.0,3,4,1,2,1,1,1,4,2,0,"(21.924, 41.0]"
2,3,4,2,29,83,126,2015/7/21 13:24,2,1967,1,0,3,4,2000,1,120.0,160,122,4,4,5,1,3,4,2,4,5,2,NaN,NaN,NaN,NaN,8000.0,3,3,1,2,3,2,1,4,2,1,"(41.0, 60.0]"
3,4,5,2,10,28,51,2015/7/25 17:33,2,1943,1,1,1,3,6420,1,78.0,163,170,4,4,4,1,2,4,4,4,5,4,NaN,NaN,NaN,NaN,12000.0,3,3,1,1,7,2,1,3,2,2,"(60.0, 79.0]"
4,5,4,1,7,18,36,2015/8/10 9:50,2,1994,1,1,1,12,-1,2,70.0,165,110,5,5,3,2,4,3,4,2,1,6,NaN,NaN,NaN,NaN,-2.0,4,3,1,1,1,3,2,3,-8,0,"(21.924, 41.0]"

In [13]:
test_df.loc[test_df['Age']<=41,'Age']=0
test_df.loc[(test_df['Age']>41)&(test_df['Age']<=60),'Age']=1
test_df.loc[(test_df['Age']>60)&(test_df['Age']<=79),'Age']=2
test_df.loc[(test_df['Age']>79),'Age']=3

test_df.head()

,id,survey_type,province,city,county,survey_time,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability,Age
0,8001,1,2,2,9,2015/7/24 10:30,2,1972,8,0,1,4,18000,1,100.0,155,120,4,4,4,4,3,3,2,2,5,1,5.0,12.0,2.0,3.0,-2,5,3,1,2,3,3,1,4,2,1
1,8002,1,22,66,106,2015/7/12 15:38,2,1938,1,1,1,4,20000,1,50.0,150,75,1,1,2,5,5,4,1,3,3,5,NaN,NaN,NaN,NaN,20000,1,1,2,2,7,3,3,4,2,3
2,8003,2,9,22,44,2015/7/5 9:36,2,1935,1,1,1,1,500,1,60.0,155,85,4,2,2,1,2,3,1,4,1,4,NaN,NaN,NaN,NaN,-2,1,2,1,2,7,3,1,3,4,3
3,8004,2,18,52,86,2015/7/19 10:10,2,1992,1,1,1,4,50000,1,220.0,160,126,5,5,5,1,2,2,2,4,5,5,NaN,NaN,NaN,NaN,100000,2,4,1,2,3,2,1,3,2,0
4,8005,2,24,70,110,2015/8/3 11:41,1,1990,1,1,2,1,0,1,200.0,173,130,4,5,3,4,4,4,2,2,2,2,NaN,NaN,NaN,NaN,30000,3,2,1,2,1,2,2,5,2,0

In [14]:
test_df.describe()

,id,survey_type,province,city,county,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability,Age
count,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,1078.000000,1078.000000,1079.000000,1079.000000,2.968000e+03,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000
mean,9484.500000,1.422507,15.295485,42.943059,71.242588,1.537062,1964.320081,1.350404,0.772574,1.434636,4.801550,24764.746968,1.341644,117.819340,163.677898,120.819407,3.604784,3.819407,3.791105,1.879380,2.824124,3.314690,1.919811,3.122978,4.210916,2.995620,3.116883,14.300557,0.911956,2.601483,6.244181e+04,2.879717,2.574124,1.081199,1.820081,3.263140,2.229111,1.714286,3.253706,1.089286,1.226752
std,856.932125,0.494042,8.906772,27.148988,38.513031,0.498709,17.044203,1.401234,1.047810,1.430248,3.199791,42247.632722,1.012489,99.949683,8.098360,23.041669,1.127738,1.252325,1.151849,1.323712,1.060393,1.054318,1.175660,1.393339,1.992061,1.752743,1.748131,11.205625,1.411139,1.888997,2.627339e+05,1.458799,1.094105,1.910487,0.488466,1.455495,0.931457,0.844442,2.187685,3.419612,0.907297
min,8001.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1920.000000,-8.000000,-8.000000,-8.000000,-8.000000,-3.000000,-8.000000,0.000000,100.000000,45.000000,-8.000000,-8.000000,-8.000000,1.000000,1.000000,-8.000000,-8.000000,-8.000000,-8.000000,1.000000,-8.000000,-3.000000,-8.000000,-8.000000,-3.000000e+00,-3.000000,-8.000000,-3.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.000000,-8.000000,0.000000
25%,8742.750000,1.000000,7.000000,18.000000,40.000000,1.000000,1952.000000,1.000000,1.000000,1.000000,3.000000,1500.000000,1.000000,66.000000,158.000000,105.000000,3.000000,3.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,3.000000,1.000000,3.000000,5.000000,1.000000,2.000000,1.200000e+04,2.000000,2.000000,1.000000,2.000000,3.000000,2.000000,1.000000,3.000000,2.000000,1.000000
50%,9484.500000,1.000000,15.000000,42.000000,73.000000,2.000000,1965.000000,1.000000,1.000000,1.000000,4.000000,14000.000000,1.000000,100.000000,163.000000,120.000000,4.000000,4.000000,4.000000,1.000000,3.000000,3.000000,2.000000,4.000000,5.000000,3.000000,3.000000,12.000000,1.000000,3.000000,3.985000e+04,3.000000,3.000000,1.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,1.000000
75%,10226.250000,2.000000,22.000000,66.000000,105.000000,2.000000,1977.000000,1.000000,1.000000,1.000000,6.000000,30000.000000,1.000000,140.000000,170.000000,135.000000,4.000000,5.000000,4.000000,2.000000,4.000000,4.000000,3.000000,4.000000,5.000000,5.000000,3.000000,22.000000,1.000000,3.000000,7.000000e+04,4.000000,3.000000,1.000000,2.000000,3.000000,3.000000,2.000000,4.000000,3.000000,2.000000
max,10968.000000,2.000000,31.000000,89.000000,134.000000,2.000000,1997.000000,8.000000,1.000000,9.000000,14.000000,800000.000000,4.000000,2400.000000,194.000000,213.000000,5.000000,5.000000,5.000000,8.000000,5.000000,5.000000,5.000000,5.000000,10.000000,6.000000,9.000000,48.000000,2.000000,4.000000,9.924000e+06,11.000000,5.000000,96.000000,2.000000,7.000000,3.000000,3.000000,5.000000,4.000000,3.000000

In [15]:
print(train_df['religion'].value_counts())

 1    7038
 0     846
-8     104
Name: religion, dtype: int64

In [16]:
print(train_df['nationality'].mode().iloc[0])
print(train_df['religion'].mode().iloc[0])
print(train_df['edu'].mode().iloc[0])
print(train_df['political'].mode().iloc[0])
print(train_df['health'].mode().iloc[0])
print(train_df['health_problem'].mode().iloc[0])

1
1
4
1
4
4

In [17]:
li = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
combine=[train_df,test_df]
for dataset in combine:
    dataset.loc[dataset['nationality'].isin(li[:8])==False,'nationality']=1
    dataset.loc[dataset['religion'].isin([0,1])==False,'religion']=1
    dataset.loc[dataset['religion_freq'].isin(li[:9])==False,'religion_freq']=1
    dataset.loc[dataset['edu'].isin(li)==False,'edu']=4
    dataset.loc[dataset['political'].isin(li[:4])==False,'political']=1
    dataset.loc[dataset['health'].isin(li[:5])==False,'health']=4
    dataset.loc[dataset['health_problem'].isin(li[:5])==False,'health_problem']=4

In [18]:
train_df.describe()

,id,happiness,survey_type,province,city,county,gender,birth,nationality,religion,religion_freq,edu,income,political,floor_area,height_cm,weight_jin,health,health_problem,depression,hukou,socialize,relax,learn,equity,class,work_exper,work_status,work_yr,work_type,work_manage,family_income,family_m,family_status,house,car,marital,status_peer,status_3_before,view,inc_ability,Age
count,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.00000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7.988000e+03,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,2946.000000,2946.000000,2946.000000,2946.000000,7.987000e+03,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000,7988.000000
mean,4001.603906,3.867927,1.405984,15.161617,42.583250,70.64647,1.530295,1964.702303,1.394342,0.894091,1.443916,4.895218,3.334375e+04,1.363921,115.356113,163.984977,121.575238,3.605784,3.850150,3.822609,1.893090,2.793440,3.294191,1.928643,3.139960,4.200551,2.979594,3.163272,14.503394,0.912424,2.658859,6.782375e+04,2.882699,2.601152,1.065223,1.819479,3.234477,2.229469,1.705809,3.310466,1.100275,1.203430
std,2309.864374,0.818717,0.491112,8.915476,27.184344,38.73718,0.499113,16.848414,1.463714,0.307740,1.348402,3.119692,2.331573e+05,0.925352,87.318410,8.085915,23.189541,1.070076,1.064563,1.045936,1.348626,1.069816,1.062033,1.182979,1.267597,2.018157,1.752412,1.736697,11.458117,1.386254,1.694709,2.911651e+05,1.520820,1.051287,0.786054,0.487953,1.423383,0.951588,0.958423,1.962336,3.403146,0.896303
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1921.000000,1.000000,0.000000,1.000000,1.000000,-3.000000e+00,1.000000,3.000000,114.000000,40.000000,1.000000,1.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.000000,-8.000000,-8.000000,1.000000,-8.000000,-3.000000,-8.000000,-8.000000,-3.000000e+00,-3.000000,-8.000000,-3.000000,-8.000000,1.000000,-8.000000,-8.000000,-8.000000,-8.000000,0.000000
25%,2001.750000,4.000000,1.000000,7.000000,18.000000,37.00000,1.000000,1952.000000,1.000000,1.000000,1.000000,3.000000,1.780000e+03,1.000000,64.000000,158.000000,105.000000,3.000000,3.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,3.000000,1.000000,3.000000,5.000000,1.000000,2.000000,1.300000e+04,2.000000,2.000000,1.000000,2.000000,3.000000,2.000000,1.000000,3.000000,2.000000,1.000000
50%,4003.500000,4.000000,1.000000,15.000000,42.000000,73.00000,2.000000,1965.000000,1.000000,1.000000,1.000000,4.000000,1.500000e+04,1.000000,96.000000,164.000000,120.000000,4.000000,4.000000,4.000000,1.000000,3.000000,3.000000,2.000000,3.000000,5.000000,3.000000,3.000000,12.000000,1.000000,3.000000,3.820800e+04,3.000000,3.000000,1.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,1.000000
75%,6002.250000,4.000000,2.000000,22.000000,65.000000,104.00000,2.000000,1977.000000,1.000000,1.000000,1.000000,6.000000,3.600000e+04,1.000000,130.000000,170.000000,135.250000,4.000000,5.000000,5.000000,2.000000,4.000000,4.000000,3.000000,4.000000,5.000000,5.000000,3.000000,22.000000,1.000000,3.000000,7.000000e+04,4.000000,3.000000,1.000000,2.000000,3.000000,3.000000,2.000000,4.000000,3.000000,2.000000
max,8000.000000,5.000000,2.000000,31.000000,89.000000,134.00000,2.000000,1997.000000,8.000000,1.000000,9.000000,14.000000,9.999990e+06,4.000000,1300.000000,191.000000,260.000000,5.000000,5.000000,5.000000,8.000000,5.000000,5.000000,5.000000,5.000000,10.000000,6.000000,9.000000,55.000000,2.000000,4.000000,9.999992e+06,50.000000,5.000000,30.000000,2.000000,7.000000,3.000000,3.000000,5.000000,4.000000,3.000000

In [20]:
from xgboost import XGBClassifier

In [24]:
train_df=train_df.drop(['survey_time'],axis=1)
X=train_df[2:]
Y=train_df['happiness']
model = XGBClassifier()
model.fit(X,Y)

XGBoostError: b'[14:00:35] /workspace/src/objective/multiclass_obj.cu:61: Check failed: preds.Size() == (static_cast<size_t>(param_.num_class) * info.labels_.Size()) SoftmaxMultiClassObj: label size and pred size does not match\n\nStack trace returned 10 entries:\n[bt] (0) /home/ning/anaconda2/envs/py36/xgboost/libxgboost.so(dmlc::StackTrace()+0x3d) [0x7f6287e9b5cd]\n[bt] (1) /home/ning/anaconda2/envs/py36/xgboost/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x18) [0x7f6287e9b9c8]\n[bt] (2) /home/ning/anaconda2/envs/py36/xgboost/libxgboost.so(xgboost::obj::SoftmaxMultiClassObj::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*)+0x152) [0x7f6288081aa2]\n[bt] (3) /home/ning/anaconda2/envs/py36/xgboost/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x362) [0x7f6287f121e2]\n[bt] (4) /home/ning/anaconda2/envs/py36/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7f6287e93ab5]\n[bt] (5) /home/ning/anaconda2/envs/py36/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f62e4b6cec0]\n[bt] (6) /home/ning/anaconda2/envs/py36/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f62e4b6c87d]\n[bt] (7) /home/ning/anaconda2/envs/py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f62e4d81e2e]\n[bt] (8) /home/ning/anaconda2/envs/py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12865) [0x7f62e4d82865]\n[bt] (9) /home/ning/anaconda2/envs/py36/bin/python(_PyObject_FastCallDict+0x8b) [0x55e62c170d7b]\n\n'